"""Rendering guards for the published dashboard.

The page is generated by string substitution into a template, and it is
published to a public URL, so the two failure modes worth catching are a
placeholder that never got replaced and a signal count that contradicts the
rows underneath it.
"""
import importlib.util
import re
import sys
from pathlib import Path

import pytest

_SCRIPTS = Path(__file__).parent.parent / "scripts"
_SPEC = importlib.util.spec_from_file_location("render_dashboard",
                                                _SCRIPTS / "render_dashboard.py")


@pytest.fixture(scope="module")
def rd():
    sys.path.insert(0, str(_SCRIPTS))
    try:
        mod = importlib.util.module_from_spec(_SPEC)
        _SPEC.loader.exec_module(mod)
        return mod
    finally:
        sys.path.remove(str(_SCRIPTS))


def _side(player, model_prob, market_prob, ref_odds, edge):
    return {"player": player, "model_prob": model_prob,
            "model_fair_odds": round(1 / model_prob, 3),
            "market_prob": market_prob,
            "market_fair_odds": round(1 / market_prob, 3),
            "ref_odds": ref_odds, "edge": edge, "ev_at_ref": 0.0,
            "elo": 1800.0, "matches": 120}


def _payload(**overrides):
    data = {
        "generated_at": "2026-08-22T12:30:18+00:00",
        "threshold": 0.05, "n_scheduled": 40, "n_scored": 1, "n_signals": 0,
        "ref_books": {"Pinnacle": 1},
        "matches": [{
            "match_id": "1", "tournament": "Cincinnati", "tour": "atp",
            "ref_book": "Pinnacle", "ref_margin": 0.025,
            "sides": [_side("Sinner J.", 0.72, 0.70, 1.40, 0.02),
                       _side("Alcaraz C.", 0.28, 0.30, 3.10, -0.02)],
            "best_edge": 0.02, "signal": False,
        }],
        "skipped": [],
        "audit": {"information_gain": -0.00078, "matches_tested": 55124,
                   "backtest_roi": 0.0135, "backtest_t": 0.48, "backtest_n": 1898},
    }
    data.update(overrides)
    return data


def test_no_placeholder_survives_rendering(rd):
    """A missed substitution would ship a literal __TOKEN__ to a public page."""
    html = rd.render(_payload())
    leftovers = re.findall(r"__[A-Z_]+__", html)
    assert leftovers == [], f"unersetzte Platzhalter: {set(leftovers)}"


def test_no_placeholder_survives_with_skips_and_signals(rd):
    """The skipped block and the signal banner are separate template paths,
    so exercise them too -- an empty card takes the other branch of each."""
    data = _payload(n_signals=1, skipped=[{"match": "A vs B", "tournament": "X",
                                            "reason": "zu wenig Matches"}])
    data["matches"][0]["signal"] = True
    html = rd.render(data)
    assert re.findall(r"__[A-Z_]+__", html) == []
    assert "A vs B" in html and "zu wenig Matches" in html


def test_signal_banner_matches_the_data(rd):
    """The headline must not claim signals the table does not show."""
    assert "Kein Signal auf dieser Karte" in rd.render(_payload(n_signals=0))
    hit = rd.render(_payload(n_signals=2))
    assert "2 Partie(n) über der Schwelle" in hit
    assert "Kein Signal" not in hit


def test_audit_numbers_reach_the_page(rd):
    """The page must carry the no-edge finding -- a divergence table without
    it reads as a tip sheet."""
    html = rd.render(_payload())
    assert "-0.00078" in html
    # Grouped with a narrow no-break space (U+202F), so match on the digits
    # rather than pinning the separator character.
    assert re.search(r"55\s*124", html)
    assert "0.48" in html


def test_every_match_names_its_reference_book(rd):
    """Pinnacle covers only some matches; the row must say which book was
    actually used rather than implying Pinnacle throughout."""
    data = _payload()
    data["matches"][0]["ref_book"] = "Betway"
    html = rd.render(data)
    assert "Betway" in html


def test_percentages_are_rendered_not_raw_floats(rd):
    html = rd.render(_payload())
    assert "72.0" in html          # model_prob 0.72 -> 72.0 %
    assert "0.72<" not in html     # never the raw fraction


def test_theme_tokens_defined_outside_media_queries(rd):
    """The un-stamped 'system' theme resolves against bare :root. A colour
    defined only inside a media or [data-theme] block renders one theme's
    text on the other theme's ground."""
    html = rd.render(_payload())
    root_block = html.split(":root {", 1)[1].split("}", 1)[0]
    for token in ("--bg", "--text", "--accent", "--border", "--pos", "--neg"):
        assert token in root_block, f"{token} fehlt im Basis-:root"


def _ta_payload():
    """A card with one model-scored match and one Tennis Abstract fallback."""
    data = _payload()
    data["matches"].append({
        "match_id": "2", "tournament": "Winston Salem", "tour": "atp",
        "ref_book": "Betway", "ref_margin": 0.06, "method": "ta_elo",
        "sides": [
            {**_side("Pierre Hugues Herbert", 0.699, 0.442, 2.10, 0.257), "matches": None},
            {**_side("Kenta Miyoshi", 0.301, 0.558, 1.62, -0.257), "matches": None},
        ],
        "best_edge": 0.257, "signal": False,
    })
    data["matches"][0]["method"] = "model"
    data["n_scored"] = 2
    return data


def test_elo_fallback_rows_carry_no_ev_number(rd):
    """A pure Elo forecast has no market input and sits ~10.6% from the price
    on average. Printing that gap as value would read as a huge bet on a match
    the model cannot score at all."""
    html = rd.render(_ta_payload())
    assert "Kein EV-Wert" in html
    assert "+25.7" not in html and "25,7" not in html


def test_elo_fallback_is_a_separate_section(rd):
    """The two methods must never share a table -- their numbers are not
    comparable."""
    html = rd.render(_ta_payload())
    assert "Ohne Modellabdeckung" in html
    assert html.index("Modellbewertung") < html.index("Ohne Modellabdeckung")
    # The model match keeps its edge badge.
    assert "+2.0" in html or "+2,0" in html


def test_fallback_players_show_ta_elo_not_a_match_count(rd):
    """`matches: None` marks a player our own history does not cover; showing
    '0 Matches' next to a rating would misstate why the row exists."""
    html = rd.render(_ta_payload())
    assert "TA-Elo 1800" in html
    assert "None Matches" not in html


def test_page_without_fallback_matches_omits_the_section(rd):
    html = rd.render(_payload())
    assert "Ohne Modellabdeckung" not in html


def test_ev_is_the_headline_number_not_edge(rd):
    """Edge is (forecast - market). Both forecasts sum to 1 and both de-vigged
    market probabilities sum to 1, so the two edges are always exact mirrors --
    true arithmetic, useless for deciding a bet. EV uses each side's own odds
    and is not symmetric."""
    html = rd.render(_payload())
    assert "EV bei Quote" in html
    assert "Warum der Edge auf beiden Seiten gleich" in html


def test_both_sides_carry_their_own_ev(rd):
    data = _payload()
    a, b = data["matches"][0]["sides"]
    a["ev_at_ref"], b["ev_at_ref"] = 0.084, -0.132
    html = rd.render(data)
    assert "+8.4" in html and "-13.2" in html


def test_edge_still_visible_but_secondary(rd):
    """The threshold is defined on edge, so it stays on the page -- just not
    where the eye lands first."""
    html = rd.render(_payload())
    assert "Edge +2.0" in html or "Edge&nbsp;+2.0" in html or "Edge " in html


def test_row_carries_its_playing_day(rd):
    """The card spans several days now. Without the date every row reads as
    today's match, which is how a finished match passed for an upcoming one
    in the first place."""
    data = _payload()
    data["matches"][0]["date"] = "2026-08-23"
    html = rd.render(data)
    assert "23.08." in html
    assert "So" in html          # Sunday


def test_row_without_a_date_renders_without_a_chip(rd):
    """Payloads built before the date column exist; they must still render."""
    html = rd.render(_payload())
    assert re.findall(r"__[A-Z_]+__", html) == []
    assert "chip day" not in html


def test_unparsable_date_does_not_break_the_page(rd):
    data = _payload()
    data["matches"][0]["date"] = "morgen"
    assert "chip day" not in rd.render(data)
