"""Rendering guards for the published dashboard.

The page is generated by string substitution into a template, and it is
published to a public URL, so the two failure modes worth catching are a
placeholder that never got replaced and a signal count that contradicts the
rows underneath it.
"""
import importlib.util
import re
import sys
from pathlib import Path

import pytest

_SCRIPTS = Path(__file__).parent.parent / "scripts"
_SPEC = importlib.util.spec_from_file_location("render_dashboard",
                                                _SCRIPTS / "render_dashboard.py")


@pytest.fixture(scope="module")
def rd():
    sys.path.insert(0, str(_SCRIPTS))
    try:
        mod = importlib.util.module_from_spec(_SPEC)
        _SPEC.loader.exec_module(mod)
        return mod
    finally:
        sys.path.remove(str(_SCRIPTS))


def _side(player, model_prob, market_prob, ref_odds, edge):
    return {"player": player, "model_prob": model_prob,
            "model_fair_odds": round(1 / model_prob, 3),
            "market_prob": market_prob,
            "market_fair_odds": round(1 / market_prob, 3),
            "ref_odds": ref_odds, "edge": edge, "ev_at_ref": 0.0,
            "elo": 1800.0, "matches": 120}


def _payload(**overrides):
    data = {
        "generated_at": "2026-08-22T12:30:18+00:00",
        "threshold": 0.05, "n_scheduled": 40, "n_scored": 1, "n_signals": 0,
        "ref_books": {"Pinnacle": 1},
        "matches": [{
            "match_id": "1", "tournament": "Cincinnati", "tour": "atp",
            "ref_book": "Pinnacle", "ref_margin": 0.025,
            "sides": [_side("Sinner J.", 0.72, 0.70, 1.40, 0.02),
                       _side("Alcaraz C.", 0.28, 0.30, 3.10, -0.02)],
            "best_edge": 0.02, "signal": False,
        }],
        "skipped": [],
        "audit": {"information_gain": -0.00078, "matches_tested": 55124,
                   "backtest_roi": 0.0135, "backtest_t": 0.48, "backtest_n": 1898},
    }
    data.update(overrides)
    return data


def test_no_placeholder_survives_rendering(rd):
    """A missed substitution would ship a literal __TOKEN__ to a public page."""
    html = rd.render(_payload())
    leftovers = re.findall(r"__[A-Z_]+__", html)
    assert leftovers == [], f"unersetzte Platzhalter: {set(leftovers)}"


def test_no_placeholder_survives_with_skips_and_signals(rd):
    """The skipped block and the signal banner are separate template paths,
    so exercise them too -- an empty card takes the other branch of each."""
    data = _payload(n_signals=1, skipped=[{"match": "A vs B", "tournament": "X",
                                            "reason": "zu wenig Matches"}])
    data["matches"][0]["signal"] = True
    html = rd.render(data)
    assert re.findall(r"__[A-Z_]+__", html) == []
    assert "A vs B" in html and "zu wenig Matches" in html


def test_signal_banner_matches_the_data(rd):
    """The headline must not claim signals the table does not show."""
    assert "Kein Signal auf dieser Karte" in rd.render(_payload(n_signals=0))
    hit = rd.render(_payload(n_signals=2))
    assert "2 Partie(n) über der Schwelle" in hit
    assert "Kein Signal" not in hit


def test_audit_numbers_reach_the_page(rd):
    """The page must carry the no-edge finding -- a divergence table without
    it reads as a tip sheet."""
    html = rd.render(_payload())
    assert "-0.00078" in html
    # Grouped with a narrow no-break space (U+202F), so match on the digits
    # rather than pinning the separator character.
    assert re.search(r"55\s*124", html)
    assert "0.48" in html


def test_every_match_names_its_reference_book(rd):
    """Pinnacle covers only some matches; the row must say which book was
    actually used rather than implying Pinnacle throughout."""
    data = _payload()
    data["matches"][0]["ref_book"] = "Betway"
    html = rd.render(data)
    assert "Betway" in html


def test_percentages_are_rendered_not_raw_floats(rd):
    html = rd.render(_payload())
    assert "72.0" in html          # model_prob 0.72 -> 72.0 %
    assert "0.72<" not in html     # never the raw fraction


def test_theme_tokens_defined_outside_media_queries(rd):
    """The un-stamped 'system' theme resolves against bare :root. A colour
    defined only inside a media or [data-theme] block renders one theme's
    text on the other theme's ground."""
    html = rd.render(_payload())
    root_block = html.split(":root {", 1)[1].split("}", 1)[0]
    for token in ("--bg", "--text", "--accent", "--border", "--pos", "--neg"):
        assert token in root_block, f"{token} fehlt im Basis-:root"
